[package]
name = "doradura"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
teloxide = { version = "0.12", features = ["macros"] }
log = "0.4"
pretty_env_logger = "0.4"
tokio = { version = "1.8", features = ["full"] }
url = "2.5.0"
shellexpand = "3.1.0"
uuid = "1.1"
rand = "0.8"
reqwest = "0.11"  # For making HTTP requests
select = "0.5"    # For parsing HTML
shell-escape = "0.1.5"
wiremock = "0.4"
thiserror = "1.0"
