[package]
name = "doradura"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
teloxide = { version = "0.12", features = ["macros"] }
log = "0.4"
pretty_env_logger = "0.4"
simplelog = "0.11"
tokio = { version = "1.8", features = ["full"] }
url = "2.5.0"
shellexpand = "3.1.0"
uuid = "1.1"
rand = "0.8"
reqwest = "0.11"  # For making HTTP requests
select = "0.5"    # For parsing HTML
shell-escape = "0.1.5"
wiremock = "0.4"
thiserror = "1.0"
anyhow = "1.0.66"
async-trait = "0.1.50"
rusqlite = "0.31.0"
r2d2 = "0.8"
r2d2_sqlite = "0.24"
tokio-retry = "0.3"
regex = "1.10.5"
once_cell = "1.19"
cc = "1.1.6"
dotenvy = "0.15"
base64 = "0.22.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
cc = "1.1.6"
