{
  "build": {
    "builder": "DOCKERFILE",
    "dockerfilePath": "./Dockerfile.bot-api.secure"
  },
  "deploy": {
    "numReplicas": 1,
    "sleepApplication": false,
    "restartPolicyType": "ON_FAILURE",
    "restartPolicyMaxRetries": 10,
    "healthcheckPath": "/",
    "healthcheckTimeout": 100
  },
  "env": {
    "API_ID": "",
    "API_HASH": "",
    "HTTP_PORT": "8081"
  }
}